// Package stats ranks mistakes and renders errors/stats.md.
package stats

import (
	"fmt"
	"sort"
	"strings"
	"time"

	"engimprove/internal/data"
)

// GeneratedMarker heads every generated stats file.
const GeneratedMarker = "<!-- generated by scripts/engstats; do not edit -->"

type counter struct {
	key   string
	extra string
	count int
	last  string
}

func rank(entries []data.Entry, key func(data.Entry) (string, string)) []counter {
	index := map[string]*counter{}
	for _, e := range entries {
		k, extra := key(e)
		c, ok := index[k]
		if !ok {
			c = &counter{key: k, extra: extra}
			index[k] = c
		}
		c.count++
		if e.Date > c.last {
			c.last = e.Date
		}
	}
	out := make([]counter, 0, len(index))
	for _, c := range index {
		out = append(out, *c)
	}
	sort.Slice(out, func(i, j int) bool {
		if out[i].count != out[j].count {
			return out[i].count > out[j].count
		}
		return out[i].key < out[j].key
	})
	return out
}

func head(rows []counter, n int) []counter {
	if len(rows) < n {
		return rows
	}
	return rows[:n]
}

func bar(count, maxCount, width int) string {
	if maxCount == 0 {
		return ""
	}
	n := count * width / maxCount
	if n == 0 && count > 0 {
		n = 1
	}
	return strings.Repeat("█", n)
}

func byCategory(e data.Entry) (string, string) { return e.Category, e.Kind }
func byRule(e data.Entry) (string, string)     { return e.Rule, e.Category }
func byKind(e data.Entry) (string, string)     { return e.Kind, "" }
func byText(e data.Entry) (string, string)     { return e.TextID, e.Date }

// Render is the terminal report.
func Render(entries []data.Entry, top int, color bool) string {
	var b strings.Builder
	dim, bold, accent, reset := "", "", "", ""
	if color {
		dim, bold, accent, reset = "\x1b[2m", "\x1b[1m", "\x1b[36m", "\x1b[0m"
	}

	categories := rank(entries, byCategory)
	rules := rank(entries, byRule)
	kinds := rank(entries, byKind)
	texts := rank(entries, byText)

	first, last := "-", "-"
	if len(entries) > 0 {
		dates := make([]string, 0, len(entries))
		for _, e := range entries {
			dates = append(dates, e.Date)
		}
		sort.Strings(dates)
		first, last = dates[0], dates[len(dates)-1]
	}

	perText := 0.0
	if len(texts) > 0 {
		perText = float64(len(entries)) / float64(len(texts))
	}

	fmt.Fprintf(&b, "%s%d mistakes%s across %s%d texts%s  %s%s → %s%s  %s%.1f per text%s\n\n",
		bold, len(entries), reset, bold, len(texts), reset, dim, first, last, reset, dim, perText, reset)

	section := func(title string, rows []counter) {
		if len(rows) == 0 {
			return
		}
		fmt.Fprintf(&b, "%s%s%s\n", accent, title, reset)
		maxCount := rows[0].count
		width := 0
		for _, r := range rows {
			width = max(width, len(r.key))
		}
		width = min(width, 46)
		for _, r := range rows {
			key := r.key
			if len(key) > width {
				key = key[:width-1] + "…"
			}
			fmt.Fprintf(&b, "  %-*s %s%4d%s %s%-20s%s %s%s%s\n",
				width, key, bold, r.count, reset, accent, bar(r.count, maxCount, 20), reset, dim, r.extra, reset)
		}
		b.WriteString("\n")
	}

	section("TOP CATEGORIES", head(categories, top))
	section("TOP RULES", head(rules, top))
	section("BY KIND", kinds)
	section("RECENT TEXTS", head(texts, 8))
	return b.String()
}

// Markdown is the content of errors/stats.md.
func Markdown(entries []data.Entry, top int) string {
	var b strings.Builder
	categories := rank(entries, byCategory)
	rules := rank(entries, byRule)
	kinds := rank(entries, byKind)
	texts := rank(entries, byText)

	fmt.Fprintf(&b, "%s\n\n# Stats\n\n", GeneratedMarker)
	fmt.Fprintf(&b, "Обновлено: %s · ошибок: %d · текстов: %d\n\n",
		time.Now().Format("2006-01-02 15:04"), len(entries), len(texts))

	if len(entries) == 0 {
		b.WriteString("База пуста. Первый разбор наполнит её.\n")
		return b.String()
	}

	b.WriteString("## Repeat offenders — categories\n\n| category | kind | count | last seen |\n|---|---|---|---|\n")
	for _, r := range head(categories, top) {
		fmt.Fprintf(&b, "| `%s` | %s | %d | %s |\n", r.key, r.extra, r.count, r.last)
	}

	b.WriteString("\n## Repeat offenders — rules\n\n| rule | category | count | last seen |\n|---|---|---|---|\n")
	for _, r := range head(rules, top) {
		fmt.Fprintf(&b, "| %s | `%s` | %d | %s |\n", r.key, r.extra, r.count, r.last)
	}

	b.WriteString("\n## By kind\n\n| kind | count |\n|---|---|\n")
	for _, r := range kinds {
		fmt.Fprintf(&b, "| %s | %d |\n", r.key, r.count)
	}

	b.WriteString("\n## Texts\n\n| text | date | mistakes |\n|---|---|---|\n")
	for _, r := range head(texts, 20) {
		fmt.Fprintf(&b, "| %s | %s | %d |\n", r.key, r.extra, r.count)
	}
	return b.String()
}

// WriteMarkdown regenerates errors/stats.md with the default top size.
func WriteMarkdown(s data.Store, entries []data.Entry) error {
	return data.WriteFile(s.Path("errors", "stats.md"), []byte(Markdown(entries, 10)))
}
